import type { NextPage } from "next";
import { useCookies } from "react-cookie";
import Head from "next/head";

import { GetServerSideProps } from "next";
import { motion, Variants } from "framer-motion";

import LoginInputs from "../../components/LoginInputs/LoginInputs";

import GoogleIcon from "@mui/icons-material/Google";
import Link from "next/link";

import FreeSongs from "../../components/FreeSongs/FreeSongs";
import Logo from "../../components/Logo/Logo";

import { Track } from "../../interfaces/tracks";

import styles from "../../styles/Home.module.css";
import LanguageSelector from "../../components/LanguageSelector/LanguageSelector";
import { useI18N } from "../../context/i18";
interface parsedTracks {
  parsedTracks: Track[];
}

export const getServerSideProps: GetServerSideProps = async () => {
  const BASE_URL_SPOTIFY = process.env.NEXT_PUBLIC_BACKEND_SPOTIFY_BACKEND;
  const response = await fetch(`${BASE_URL_SPOTIFY}/track`);
  const result = await response.json();

  //This is necessary. What it does is that Next does not render all the tracks, but only the first 10 tracks so that the app is not so heavy.
  const parsedTracks = result.data.slice(13, 20).map((track: Track) => track);

  return {
    props: { parsedTracks },
  };
};

const Login = ({ parsedTracks }: parsedTracks) => {
  const { t } = useI18N();

  return (
    <>
      <Head>
        <title>Log In</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.loginHeader}>
        <picture className={styles.logoMain}>
          <img src="/Images/beatgo_logo_grey.png" alt="BeatGO Logo" />
        </picture>
        <LanguageSelector />
      </div>

      <main className={styles.indexMain}>
        <motion.section
          className={styles.loginWrapper}
          initial={{ opacity: 0, x: 200 }}
          animate={{ opacity: 1, x: 0 }}
          exit={{ opacity: 0, x: -200 }}
          transition={{ duration: 0.5 }}
        >
          {/* <DemoAppComponent /> */}
          <div className={styles.logIn_signUp_Div}>
            <LoginInputs />
            <section className={styles.signUpSection}>
              <span>{t("login").notAccount}</span>
              <Link href={"/signup"}>
                <a className={styles.colorLink}>{t("login").signup}</a>
              </Link>
            </section>
          </div>
        </motion.section>
        <FreeSongs tracks={parsedTracks} />
      </main>
    </>
  );
};

export default Login;
