import Layout from "../../components/Layout/Layout";

import styles from "./styles.module.css";
import Head from "next/head";
import TabPanel from "../../components/TabPanel/TabPanel";
import { useRouter } from "next/router";
import { useGetPlaylistDetailsQuery } from "../../redux/playlistAPI";
import CreatePlaylist from "../../components/Playlist/CreatePlaylist";
import Searchbar from "../../components/Playlist/Searchbar/Searchbar";
import TrackList from "../../components/TrackList/TrackList";
import { useI18N } from "../../context/i18";
import { useEffect, useState } from "react";

const Playlist = () => {
  const { query } = useRouter();
  const { t } = useI18N();

  const {
    data: playlist,
    isLoading: isLoadingPlaylist,
    isSuccess,
    error: playlistError,
  } = useGetPlaylistDetailsQuery(query.playlistID);

  const [imagePlayList, setImagePlayList] = useState<string>(playlist?.data?.image);
  const [title, setTitle] = useState<string>(playlist?.data?.title);
  const [description, setDescription] = useState(playlist?.data?.description);
  const [change, setChange] = useState<boolean>(false)

  const tracksExist = playlist?.data?.tracks?.length > 0;
  
  useEffect(()=>{
    setTitle(playlist?.data?.title)
    setDescription(playlist?.data?.description)
    setImagePlayList(playlist?.data?.image)
  },[playlist, change])

  useEffect(() => {    
    const getupdatedData = async() =>{
      const response = await fetch(`http://localhost:4002/playlist/${query.playlistID}`,{
        method:'GET',
        headers:{
          Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzRkMzg5YjRkZTk5YzgyOTE5ZjAyYjciLCJ1c2VybmFtZSI6ImNhcmxvcyIsImlhdCI6MTY2NjAxNTY2NywiZXhwIjoxNjY2NDQ3NjY3fQ.Ab1oBxGAQVaQIX5jnHxYWsETMUNn_Mp1OyA7gFCvN0M'
        }
      })
      const data = await response.json();
      setImagePlayList(data?.data?.image)
      setDescription(data?.data?.description)
      setTitle(data?.data?.title)
    }
    getupdatedData()
  },[change])
  
  return (
    <>
      <Head>
        <title>{`${t("additional").app_name} - ${t("additional").playlist}`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {change}
      <Layout>
        <CreatePlaylist
          playlistId={true}
          title={title}
          image={imagePlayList}
          setImagePlayList={setImagePlayList}
          setTitle={setTitle}
          setDescription={setDescription}
          change={change}
          setChange={setChange}
          description={description}
        />
        {tracksExist ? (
          <>
            <div className={styles.playlist_tracks}>
              <TrackList
                name={playlist?.data?.title}
                tracks={playlist?.data?.tracks}
              />
            </div>
            <Searchbar />
          </>
        ) : (
          <>
            <Searchbar />
            <div className={styles.playlist_tracks}>
              <TrackList
                name={playlist?.data?.title}
                tracks={playlist?.data?.tracks}
              />
            </div>
          </>
        )}
      </Layout>
    </>
  );
};

export default Playlist;
