import Layout from "../../components/Layout/Layout";

import styles from "./styles.module.css";
import Head from "next/head";
import TabPanel from "../../components/TabPanel/TabPanel";
import { useRouter } from "next/router";
import { useGetPlaylistDetailsQuery } from "../../redux/playlistAPI";
import CreatePlaylist from "../../components/Playlist/CreatePlaylist";
import Searchbar from "../../components/Playlist/Searchbar/Searchbar";

type Props = {};

const Playlist = (props: Props) => {
  const { query } = useRouter();

  const {
    data: playlist,
    isLoading: isLoadingPlaylist,
    error: playlistError,
  } = useGetPlaylistDetailsQuery(query.playlistID);

  return (
    <>
      <Head>
        <title>Create Playlist</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <CreatePlaylist />
        <Searchbar />
        <TabPanel data={playlist?.data} />
      </Layout>
    </>
  );
};

export default Playlist;
