import Layout from '../../components/Layout/Layout';
import ContactsContainer from '../../components/ContactsContainer/ContactsContainer';
import ChatRoom from '../../components/ChatRoom/ChatRoom';

import styles from './styles.module.css';
import Head from 'next/head';
import { useI18N } from '../../context/i18';



type Props = {};

const Chat = (props: Props) => {
  const { t } = useI18N();
  return (
    <>
      <Head>
        <title>
          {`${t('additional').app_name} - ${t('headers').headerChat}`}
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className={styles.chat_container}>
          <h1> {t('additional').messages}</h1>
          <div className={styles.main_content}>
            <ChatRoom />
            <ContactsContainer />
          </div>
        </div>
      </Layout>
    </>
  );
};

export default Chat;
