import styles from './styles.module.css';
import Layout from '../../components/Layout/Layout';
import Head from 'next/head';
import Image from 'next/image';
import Button from '@mui/material/Button';

import { useGetUserQuery } from '../../redux/userAPI';
import { useI18N } from '../../context/i18';

type Props = {};

const UserConfig = (props: Props) => {
  const userID = '6352a8d8c3b98403b31aaf75';
  const { data: user, isSuccess: isSuccessUser } = useGetUserQuery(userID);
  const { t } = useI18N();

  console.log(user);

  return (
    <>
      <Head>
        <title>
          {`${t('additional').app_name} - ${t('headers').headerConfig}`}
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className={styles.configuration_container}>
          <h1>{t('headers').headerConfig}</h1>
          <div className={styles.form_container}>
            <div className={styles.image_container}>
              <Image
                src="/Images/contact_default.png"
                alt="contact"
                width={100}
                height={100}
                layout="fixed"
              />
              <Button
                variant="contained"
                className={styles.change_button}
                sx={{ background: '#1bb16b', color: 'black' }}
              >
                Change Profile Picture
              </Button>
            </div>
          </div>
          <form action="" className={styles.config_form}>
            <div className={styles.input_group}>
              <label className={styles.label}>Username</label>
              <input
                autoComplete="off"
                name="Name"
                id="Name"
                className={styles.input}
                type="text"
                value={user?.data.username}
              />
            </div>
            <div className={styles.input_group}>
              <label className={styles.label}>Phone</label>
              <input
                autoComplete="off"
                name="lastName"
                id="lastName"
                className={styles.input}
                type="text"
                value={user?.data.phone}
              />
            </div>
            <div className={styles.input_group}>
              <label className={styles.label}>Email address</label>
              <input
                autoComplete="off"
                name="Email"
                id="Email"
                className={styles.input}
                type="email"
                value={user?.data.email}
              />
            </div>
            <Button
              variant="contained"
              className={styles.change_button}
              sx={{ width: '20%' }}
            >
              Save
            </Button>
          </form>
        </div>
      </Layout>
    </>
  );
};

export default UserConfig;
