import Head from 'next/head';
import Layout from '../../components/Layout/Layout';
import { useI18N } from '../../context/i18';
import Banner from '../../components/Banner/Banner';
import TrackList from '../../components/TrackList/TrackList';
import { useGetArtistsQuery } from '../../redux/artistAPI';

type Props = {};

const Favorites = (props: Props) => {
  const { t } = useI18N();
  //Data para maquetar, hacer la query correcta para las liked tracks del user
  const { data: tracks, isLoading, isError } = useGetArtistsQuery(undefined);
  console.log(tracks.data[0].tracks);
  return (
    <>
      <Head>
        <title>{`${t('additional').app_name} - ${
          t('headers').headerFavorites
        }`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Banner user={'alejo61094'} total={21} />
        <TrackList
          name="Liked Songs"
          tracks={tracks.data[0].tracks}
          heightValue={35}
        />
      </Layout>
    </>
  );
};

export default Favorites;
