import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import LoginInputs from "../components/LoginInputs/LoginInputs";

import GoogleIcon from "@mui/icons-material/Google";
import Link from "next/link";
import DemoAppComponent from "../components/DemoApp/DemoAppComponent";

import FreeSongs from "../components/FreeSongs/FreeSongs";
import Logo from "../components/Logo/Logo";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Spotify Impostor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Logo Height={80} Width={110} ClassName={"logoMain"} />

      <main className={styles.indexMain}>
        <section className={styles.loginWrapper}>
          {/* <DemoAppComponent /> */}
          <div className={styles.logIn_signUp_Div}>
            <LoginInputs />
            <section className={styles.googleLogin}>
              <GoogleIcon />
              <span>Continue with Google</span>
            </section>
            <section className={styles.signUpSection}>
              <span>
                Don<span>&#39;</span>t have an account?
              </span>
              <Link href={"/signup"}>
                <a className={styles.colorLink}>Sign Up</a>
              </Link>
            </section>
          </div>
        </section>
        <FreeSongs />
      </main>
    </>
  );
};

export default Home;
